%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Right Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 519.2757568359375
Camera1.fy: 519.2757568359375
Camera1.cx: 642.5560302734375
Camera1.cy: 357.8195495605469
# distortion parameters
Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

# Camera resolution
Camera.width: 1280
Camera.height: 720

# Camera frames per second 
Camera.fps: 10

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

Stereo.ThDepth: 62.28
Stereo.b: 0.12

# Depth map values factor
RGBD.DepthMapFactor: 1.0

# Transformation from body-frame (imu) to left camera
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   #data: [-0.000014, -0.0139993, 0.999902, 0.023,
    #       -0.999998, 0.0019999, 0.000014, 0.0, 
     #      -0.0019999, -0.9999, -0.0139993, -0.002,
      #      0.0, 0.0, 0.0, 1.0]
   data: [0.0018428485898334514, -0.9999695723936832, -0.007560509831067599, -0.0020000000949949026,
           -0.008586665592459545, 0.007544420440919406, -0.9999345248627296, -0.023061001673340797, 
           0.9999612873493375, 0.0019076477770695486, -0.00857250236981136, 0.00021700002253055573,
            0.0, 0.0, 0.0, 1.0]
# Do not insert KFs when recently lost
IMU.InsertKFsWhenLost: 0

# IMU noise (Use those from VINS-mono)
IMU.NoiseGyro: 0.007 # 3 # 2.44e-4 #1e-3 # rad/s^0.5
IMU.NoiseAcc: 0.0016 #2 # 1.47e-3 #1e-2 # m/s^1.5
IMU.GyroWalk: 0.0019474000437185168 # rad/s^1.5
IMU.AccWalk: 0.000250899989623576 # m/s^2.5
IMU.Frequency: 200.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1250

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
